name: Create a release build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: oven/bun
    name: Build and Release
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false